### ISSUE TITLE
Keras.NET のバージョンは 3.8.6 ではなく 3.8.5ではないか

### ISSUE THREAD

**Issue by currysita** [kmycode/kmy-keiba#220]
初めまして。
こちらのプロジェクトをローカルで実験していたのですが、
> KmyKeiba.ML/KmyKeiba.ML.csproj
というプロジェクトファイルで Keras.NET を読み込んでいると思います。
> <PackageReference Include="Keras.NET" Version="3.8.6" />。

NuGetパッケージマネージャー を見ると、 Keras.NET の最新版がは 3.8.5 のようです。
こちらでも確認しました。
https://www.nuget.org/packages/Keras.NET/3.8.5?_src=template

できればバージョンを修正して頂いた方が良いかと思います。
至らない点があればご指摘ください。

**Comment by kmycode** [comment]
ご連絡ありがとうございます。

私が`Keras.NET`をインストールした時は、特にバージョンは指定してなかったと思います。

```
Install-Package Keras.NET
```

`ML.csproj`に`3.8.6`が保存されてしまった理由は不明ですが、少なくとも手動の編集をした記憶はないです。
可能かは分かりませんが、バージョン`3.8.6`が削除された可能性もあります。ないのであれば`3.8.5`のまま運用いただいて差し支えありませんし、パッケージのインストール時にエラーが出ても困りますのでコードも修正したほうがよさそうですね。

ちなみに`Keras.NET`のGitHubリポジトリでは、`3.8.6`が存在するようです。

https://github.com/SciSharp/Keras.NET/releases

**Comment by currysita** [comment]
早速お返事頂けると思って無くて驚きました。ありがとうございます。
Nugetのパッケージマネージャーよりgithubのリポジトリを見た方が確実なのかもしれないですね。
失礼しました。
バージョンにこだわりが無いのであれば、気にせずそのときのバージョンを使用したいと思います。
ありがとうございました。
